### ISSUE TITLE
Missed libraries

### ISSUE THREAD

**Issue by DirtyRacer1337** [beeyev/thumbor-s3-docker#31]
Just noticed that few python libraries missed in docker container

- for `Detection` needs [opencv-python-headless](https://pypi.org/project/opencv-python-headless/)
- for `Lazy Detection` needs [redis](https://pypi.org/project/redis/)

**Comment by DirtyRacer1337** [comment]
any news?

biggest problem that alpine not best solution for python, you have to build opencv for it

found this package, think you can add it and make symlinks to library and opencv bin to the right path
https://pkgs.alpinelinux.org/package/edge/community/x86/py3-opencv

**Comment by beeyev** [comment]
Hello, thank you very much for your findings.
I plan to work on this project this weekend, so I will attempt to address this issue. 
However, I have a question: Do you think it would be better to switch from the Alpine to the slim Debian version?
 Initially, I chose Alpine because of its small image size, but I acknowledge that it can be challenging to incorporate Python-related components into this distribution.

**Comment by DirtyRacer1337** [comment]
think switching from alpine would be easier, python also have slim-debian version, so difference probably would be like 50mb

**Comment by beeyev** [comment]
I replaced full-featured alpine version with debian based.
```
thumbor-s3:debian
thumbor-s3:7-debian
thumbor-s3:7.7-debian
```

Detection and lazy detection functionality is fully supported now.
